title: Zi-quan Wei
title_cn: 魏梓泉
logo: /assets/img/wei.jpg
description: Master student @HUST.
show_buttons: true
index_url: https://chrisa142857.github.io
project_url: https://chrisa142857.github.io/projects
publication_url: https://chrisa142857.github.io/publications
research_statement_url: https://drive.google.com/file/d/1SJgMNn493hlpMTHLE5goz4pCxzj5oLuJ/view?usp=sharing
twitter_url: https://twitter.com/ZiquanWei
linkedin_url: https://www.linkedin.com/in/%E6%A2%93%E6%B3%89-%E9%AD%8F-275800215/
rg_url: https://www.researchgate.net/profile/Ziquan-Wei
google_analytics:
theme: jekyll-theme-minimal
